#!/bin/bash -e

old_directory=`pwd`
mkdir myTemp
cp $1/. myTemp -R

cd myTemp
make testdominion
./testdominion $3 > first.out
mv first.out $old_directory
#cd $old_directory

rm -f *
cp $2/. . -R
cp $4/. . -R
make testdominion
timeout 10s ./testdominion $3 > second.out
if [ $? != 0 ]; then
	echo "Could not finish tests. Encountered an infinite loop" >> second.out
fi
mv second.out $old_directory
cd $old_directory

diff -s -y first.out second.out > diff.out
results=`tail -n 1 < diff.out`
if [ "$results" == "Files first.out and second.out are identical" ]; then
	echo "TEST PASSED"
else
	echo "TEST FAILED"
	echo "first vs second output (left vs right)"
	echo
	cat diff.out
fi

rm -rf myTemp
